---
creation_rules:
  - path_regex: cephiro/.+\.sops\.yaml
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    key_groups:
      - age:
          - age1d9ghqfdg9my9vvyuqt7fjp6fxyz40yugpaevfgxmfl7djtp4t49sasyugd
stores:
  yaml:
    indent: 2