---
cgroup:
  automount:
    enabled: false
  hostRoot: /sys/fs/cgroup
  ipam:
      mode: kubernetes
  hostFirewall:
      enabled: true
  hubble:
      relay:
        enabled: true
      ui:
        enabled: true
kubeProxyReplacement: true
securityContext:
  capabilities:
    ciliumAgent:
        - CHOWN
        - KILL
        - NET_ADMIN
        - NET_RAW
        - IPC_LOCK
        - SYS_ADMIN
        - SYS_RESOURCE
        - DAC_OVERRIDE
        - FOWNER
        - SETGID
        - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
    k8sServiceHost: api.cephiro.musai.ovh
    k8sServicePort: "6443"
