apiVersion: v1
kind: Secret
metadata:
    name: sops-age
stringData:
    age.agekey: ENC[AES256_GCM,data:2mfqBH10rSIpkmCVby2sBdSF1iRBqcmH0wwTQmWdznYAG0SCSfE8L06XXFzWWaph0Nf/r8GSFlv5nmUGWkw=,iv:yfKwT2fV2ylyABXVhPPbfJCZvpXbAA1sMSHIEaESsC4=,tag:Wq4TDdVSTHIaOPB0p0+TOA==,type:str]
sops:
    age:
        - recipient: age1d9ghqfdg9my9vvyuqt7fjp6fxyz40yugpaevfgxmfl7djtp4t49sasyugd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUDBoUmtEL2t0b0RUSllx
            d2s3aWxQUUdXK1A0cHhGOXU2WmYzZVQ2VGxjCk44R3hpaTVLSHg5RDI2OTZyMVN3
            bWtjRURDYnkwME0wMk83WkRlanBuK2cKLS0tIHozN2xNZ2JBV1cwdHZ0a0ZBbjd6
            MVdpYWE5Q05lanAvd3VyZjd4YVg0SXcKnhqrtk5Dfvcz3mOwXCHXCSg8VaFQhrML
            4vNCfxAHNJKrDSFv7zBn7h8JaeNHQ+de4xz66xW9V9j+FASNKjZHhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-26T23:20:46Z"
    mac: ENC[AES256_GCM,data:fdDNlW5Weu7vB//0aTqX2nbCYNZbehs5mOFp/12CPFsDz1MfvITL2NX2In2vAFPvdchLdHiULKPTLK7gjsNXHrZdG8m6MlR/Eyr21eq2rp9lSzLrt+y/zxH3SBwWVt5xosFIQWWTCA1DL2AyMCLx7gRtPHRsrXaP4dPvA2Rs4Io=,iv:zpNPNBEI0/LXgUV2q89yO5lpRQ1unVJt8/b8PgFXkCE=,tag:YmElgMCp+9yU11wAqSQCjw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2